Repository Checkmarx/ast-vscode-extension, pull requests merged in 2023-03, with the labels that each got.

#380 Additional Parameter info tooltip
  package.json
Labels: enhancement

#335 SCA auto scanning - scan projects from the IDE
  media/sca.css
  package.json
  src/ast_results_provider.ts
  src/extension.ts
  src/models/results.ts
  src/resultsView/ast_details_view.ts
  src/resultsView/ast_multi_step_input.ts
  src/resultsView/ast_results_provider.ts
  src/resultsView/create_scan_provider.ts
  src/resultsView/pickers.ts
  src/scaView/sca_create_scan_provider.ts
  src/scaView/sca_results_provider.ts
  src/test/7.scaResults.test.ts
  src/test/utils/constants.ts
  src/test/utils/utils.ts
  src/utils/ast/ast.ts
  src/utils/common/commands.ts
  src/utils/common/constants.ts
  src/utils/filters.ts
  src/utils/group.ts
  src/utils/interface/details.ts
  src/utils/listeners.ts
  src/utils/sast/triage.ts
  src/utils/tree/actions.ts
  src/utils/tree/treeItem.ts
Labels: feature

#387 Fix for ScanButton disabled after closing IDE during push notification
  src/extension.ts
  src/resultsView/create_scan_provider.ts
  src/scaView/sca_create_scan_provider.ts
  src/utils/listeners.ts
Labels: bug
