Repository Checkmarx/ast-vscode-extension, pull requests merged in 2025-04, with the labels that each got.

#1071 Add ASPM results section.
  .github/workflows/checkmarx-one-scan.yml
  media/auth.js
  media/riskManagement.css
  media/riskManagement.js
  package-lock.json
  package.json
  src/cx/cx.ts
  src/cx/cxMock.ts
  src/cx/cxPlatform.ts
  src/extension.ts
  src/services/authService.ts
  src/test/12.oauthAuthentication.test.ts
  src/test/4.scanIDResult.test.ts
  src/views/gptView/gptView.ts
  src/views/resultsView/astDetailsView.ts
  src/views/resultsView/astResultsProvider.ts
  src/views/riskManagementView/riskManagementService.ts
  src/views/riskManagementView/riskManagementView.ts
  src/webview/authenticationWebview.ts
Labels: feature

#1098 Fix OAuth Small Bugs
  media/auth.js
  package-lock.json
  src/commands/commonCommand.ts
  src/cx/cx.ts
  src/cx/cxMock.ts
  src/extension.ts
  src/services/authService.ts
  src/utils/listener/listeners.ts
  src/views/resultsView/astResultsProvider.ts
  src/webview/authenticationWebview.ts
Labels: bug

#1103 New design filter in ASPM section
  media/riskManagement.css
  media/riskManagement.js
  src/views/riskManagementView/constants.ts
  src/views/riskManagementView/riskManagementView.ts
Labels: bug

#1105 Adds error handling for file not found in workspace (AST-68623)
  src/commands/webViewCommand.ts
  src/cx/cx.ts
  src/utils/common/constants.ts
  src/views/gptView/gptView.ts
Labels: bug

#1110 Update AST CLI JavaScript Wrapper to version 0.0.130
  package-lock.json
  package.json
Labels: cxone
