Repository Checkmarx/ast-vscode-extension, pull requests merged in 2025-07, with the labels that each got.

#1195 Fixed Infocard closure on logout(AST-90830)
  src/commands/webViewCommand.ts
  src/extension.ts
  src/webview/authenticationWebview.ts
Labels: bug

#1171 Displayed additional traits and Risk score in ASPM results UI (AST-93137)
  media/sca.css
  package-lock.json
  package.json
  src/models/results.ts
  src/utils/interface/details.ts
  src/views/riskManagementView/riskManagementView.ts
Labels: feature

#1205 Updated logo and content (AST-98735)
  docs/logo.png
  media/icon.png
Labels: feature

#1220 Update AST CLI JavaScript Wrapper to version 0.0.138
  package-lock.json
  package.json
Labels: cxone

#1232 Update AST CLI JavaScript Wrapper to version 0.0.139
  package-lock.json
  package.json
Labels: cxone
