Repository Checkmarx/ast-vscode-extension, pull requests merged in 2025-03, with the labels that each got.

#1056 Add color to the text(AST-83670)
  media/gpt.js
  src/utils/interface/details.ts
Labels: bug

#1046 Feature/elchanan/implement oauth2 ide authentication (AST-83466)
  media/auth.css
  media/auth.js
  media/icons/error.svg
  media/icons/login.svg
  media/icons/logout.svg
  media/icons/success.svg
  package-lock.json
  package.json
  src/commands/commonCommand.ts
  src/cx/cx.ts
  src/cx/cxMock.ts
  src/cx/cxPlatform.ts
  src/cx/index.ts
  src/e2e/getScan.test.ts
  src/extension.ts
  src/services/authService.ts
  src/test/1.settings.test.ts
  src/unit/authService.test.ts
  src/unit/authValidate.test.ts
  src/unit/commonCommand.test.ts
  src/unit/mocks/vscode-mock.ts
  src/utils/common/commands.ts
  src/utils/listener/listeners.ts
  src/views/resultsView/astResultsProvider.ts
  src/webview/authenticationWebview.ts
Labels: feature

#1066 Fix choose custom states (AST-84553)
  src/utils/interface/details.ts
Labels: bug

#1072 Update AST CLI JavaScript Wrapper to version 0.0.127
  package-lock.json
  package.json
Labels: cxone

#1063 Refactor AuthService to use Axios instead of HTTP module
  package-lock.json
  package.json
  src/e2e/utils/utils.ts
  src/services/authService.ts
  src/unit/authService.test.ts
  src/webview/authenticationWebview.ts
Labels: bug
